
### 거래 이벤트 저장

POST http://localhost:8080/account/0001/transfer
Accept: application/json
Content-Type: application/json

{
  "account": {
    "number": "0001"
  },
  "amount": {
    "value": "9"
  }
}



### 잔액 조회

GET http://localhost:8080/account/0001/balance
Accept: application/json



### 거래 이벤트 스트리밍

GET http://localhost:8080/account/0001/transfer/stream
Accept: text/event-stream
